### ISSUE TITLE
appspace一直重启

### ISSUE THREAD

**Issue by zhangtianming777** [treexi/wework#31]
root@qs-virtual-machine:/home/qs/app/app-space-develop/server# docker ps
CONTAINER ID   IMAGE       COMMAND                   CREATED          STATUS                          PORTS                        NAMES
63acdb520809   mongo:6.0   "docker-entrypoint.s…"   13 minutes ago   Up 13 minutes                   127.0.0.1:27017->27017/tcp   appspace-mongo
de07d92eb7e1   appspace    "/app/docker/docker-…"   13 minutes ago   Restarting (1) 59 seconds ago                                appspace

appspace一直重启。报错是以下
Error: Cannot find module 'bsdiff-nodejs'
Require stack:
- /app/server/services/version-manager.js
- /app/server/controllers/upload.js
- /app/server/controller.js
- /app/server/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/app/server/services/version-manager.js:15:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at loader (/app/server/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (/app/server/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/app/server/controllers/upload.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at loader (/app/server/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (/app/server/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /app/server/controller.js:37:19
    at Object.<anonymous> (/app/server/controller.js:29:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at loader (/app/server/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (/app/server/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/server/services/version-manager.js',
    '/app/server/controllers/upload.js',
    '/app/server/controller.js',
    '/app/server/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app-space-server@1.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app-space-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-11-15T09_14_51_177Z-debug.log

看报错是缺少了node.js？
root@qs-virtual-machine:/home/qs/app/app-space-develop/server# docker images
REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
appspace     latest    c504f33cfcd7   18 minutes ago   569MB
mongo        6.0       a1ed927d524d   3 weeks ago      716MB

**Comment by zhangtianming777** [comment]
root@qs-virtual-machine:/home/qs/app/app-space-develop/server# node -v
v10.19.0

我node的版本是v10.19.0
