### ISSUE TITLE
上传apk文件到100%时，发生错误怎么解决？

### ISSUE THREAD

**Issue by luowei** [treexi/wework#7]
后台报错如下：
```
[DEBUG] cps:index - use set Access-Control Header
Process API POST /api/apps/upload...

  Error: Parse Error
      at socketOnEnd (_http_server.js:568:22)
      at Socket.emit (events.js:327:22)
      at Socket.EventEmitter.emit (domain.js:467:12)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by treexi** [comment]
加qq吧

**Comment by treexi** [comment]
修改配置

**Comment by treexi** [comment]
@

**Comment by xubillde** [comment]
@treexi 哪个配置
